<header class="intro">
<h1> <?php echo $this->title ?> </h1>
</header>
<div class="content">
<?php
// uses default content properties
//echo $this->literal(array('tag' => 'div', 'class' => 'content'));

$posts = $this->query(
       	   array(
	     'where' => '{?resourceUri foaf:maker <http://aksw.org/SebastianTramp>}',
	     'template' => 'post',
	     'limit' => ''
           )
         );

 echo $posts;
?>
</div>
