<header class="intro">
<h1> <?php echo $this->title ?> </h1>
</header>
<?php
// uses default content properties
//echo $this->literal(array('tag' => 'div', 'class' => 'content'));
?>
<div class="content">
<?php
$posts = $this->query(
       	   array(
	     'where' => '{?resourceUri a sioct:BlogPost}',
	     'template' => 'post',
	     'limit' => ''
           )
         );
 echo $posts;
?>
</div>
