<?php
// prepare hookline and abstract (both optional)

$created = $this->literal(array(
    'property' => 'dct:created',
    'tag' => 'p',
    'node' => true 
));

$maker = $this->query(array(
    'where' => '<'.$this->resourceUri.'> foaf:maker ?resourceUri',
    'template' => 'resource'
));

$posts = $this->query(
       	   array(
	     'where' => '{ ?resourceUri sioc:about ?post .
			   ?resourceUri a sioct:Comment .
			   filter (?post = <http://blog.aksw.org/2013/ontowiki-feature-of-the-week-lov-integration/>) }',
	     'template' => 'post',
	     'limit' => ''
           )
         );

?>
<header class="intro">
<h1> <?php echo $this->title ?></h1>
<?php echo $maker?>
<?php echo $this->date($created) ?>
</header>
<div class="content">
<p><?php
 // uses default content properties
  echo $this->literal(array('tag' => 'div', 'class' => 'content'));
?> </p>
<p>
<h1> Kommentare </h1>
<?php  echo $posts ?>
</p>
</div>
