<header class="intro">
<h1> <?php echo $this->title ?> </h1>
</header>
<?php
// uses default content properties
//echo $this->literal(array('tag' => 'div', 'class' => 'content'));
?>
<div class="content">
<nav class="nav-sidelinks">
<ul>
  <li><a href="" > Sidenav1 </a></li>
  <li><a href="" > Sidenav2 </a></li>
</ul>
</nav>
<?php
$posts = $this->query(
       	   array(
	     'where' => '{?resourceUri a sioc:Post}',
	     'template' => 'post',
	     'limit' => '10'
           )
         );
 echo $posts;
?>
</div>
